// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-V-E-aU7blmdii_vBzRLEoTkTu6AwzUE',
    appId: '1:783358986799:android:089d5257de792724b194da',
    messagingSenderId: '783358986799',
    projectId: 'i-cash-demo',
    databaseURL: 'https://i-cash-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'i-cash-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwatz11m_P-kTmyuV7Xa_T3dYf_S2cQ8',
    appId: '1:783358986799:ios:3eee1b5ff3a08831b194da',
    messagingSenderId: '783358986799',
    projectId: 'i-cash-demo',
    databaseURL: 'https://i-cash-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'i-cash-demo.firebasestorage.app',
    iosBundleId: 'com.example.iCash',
  );
}
